# Generated by Django 3.2.20 on 2023-08-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0008_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAccessCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(default='Unknown', max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
