# Generated by Django 3.2.20 on 2023-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0009_taccesscodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
