# Generated by Django 3.2.20 on 2023-08-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0012_taccesscodes_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taccesscodes',
            name='job',
        ),
        migrations.AddField(
            model_name='jobs',
            name='access_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lock.taccesscodes'),
        ),
    ]
