# Generated by Django 3.2.20 on 2023-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0013_auto_20230815_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='access_code',
        ),
        migrations.AddField(
            model_name='jobs',
            name='access_code',
            field=models.ManyToManyField(to='lock.TAccessCodes'),
        ),
    ]
