# Generated by Django 3.2.20 on 2023-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0014_auto_20230815_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='access_code',
        ),
        migrations.AddField(
            model_name='jobs',
            name='access_code',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
