# Generated by Django 3.2.20 on 2023-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0018_tregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
