# Generated by Django 3.2.20 on 2023-08-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0019_logs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logs',
            new_name='All_logs',
        ),
    ]
