# Generated by Django 3.2.20 on 2023-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0020_rename_logs_all_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_logs',
            name='image',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='all_logs',
            name='reason',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
