# Generated by Django 3.2.20 on 2023-10-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0022_auto_20231009_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Unknown', max_length=100)),
                ('image', models.TextField(default='Unknown')),
            ],
        ),
        migrations.RenameModel(
            old_name='Job',
            new_name='jobs',
        ),
        migrations.RenameModel(
            old_name='RandomFact',
            new_name='RandomFacts',
        ),
        migrations.RenameModel(
            old_name='TAccessCode',
            new_name='TAccessCodes',
        ),
        migrations.RenameModel(
            old_name='Unlocker',
            new_name='Unlockers',
        ),
        migrations.DeleteModel(
            name='AllLog',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='job_id',
            new_name='jobid',
        ),
        migrations.RenameField(
            model_name='taccesscodes',
            old_name='job_id',
            new_name='jobid',
        ),
        migrations.AlterField(
            model_name='tregistration',
            name='image',
            field=models.TextField(default='Unknown'),
        ),
    ]
