# Generated by Django 3.2.20 on 2023-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0023_auto_20231009_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='access_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Unknown', max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
